### ISSUE TITLE
Fatal error: Uncaught DivisionByZeroError 

### ISSUE THREAD

**Issue by joab40** [nohn/watermeter#89]
Got this Error.  
Reads 4 Pre Decimal Digital Digits just fine! :)
Guess it has something to do with analog digits, cant remove "remove gauge"  ( pops back when deleting in the web-gui )!?

Raw OCR: 1835
Clean OCR: 1835
Digital: 1835

Fatal error: Uncaught DivisionByZeroError: Division by zero in /usr/src/watermeter/vendor/nohn/analogmeterreader/src/AnalogMeter.php:173 Stack trace: #0 /usr/src/watermeter/vendor/nohn/analogmeterreader/src/AnalogMeter.php(69): nohn\AnalogMeterReader\AnalogMeter->processImage(false) #1 /usr/src/watermeter/classes/Reader.php(149): nohn\AnalogMeterReader\AnalogMeter->getValue() #2 /usr/src/watermeter/classes/Reader.php(49): nohn\Watermeter\Reader->readGauges() #3 /usr/src/watermeter/public/configure.php(227): nohn\Watermeter\Reader->getReadout() #4 {main} thrown in /usr/src/watermeter/vendor/nohn/analogmeterreader/src/AnalogMeter.php on line 173

**Comment by joab40** [comment]
<img width="1246" alt="Screenshot 2022-12-26 at 20 10 50" src="https://user-images.githubusercontent.com/2969281/209577599-7ef60ec5-9420-4e2a-98d7-3d8907ca3bae.png">

**Comment by joab40** [comment]
<img width="916" alt="Screenshot 2022-12-26 at 20 23 49" src="https://user-images.githubusercontent.com/2969281/209578199-d81db516-40ad-458f-9bcb-c79e98cfb3ad.png">

RaspberryPI camera image taken from nginx on : http://pi/test.jpg ( Updates every 5min )

**Comment by nohn** [comment]
Should be fixed in latest docker builds. Please try again.

**Comment by joab40** [comment]
It works, thanks a lot. :) 
Only minor warning now.. 

<img width="1097" alt="Screenshot 2022-12-27 at 16 29 11" src="https://user-images.githubusercontent.com/2969281/209688284-60469cfd-dbc9-406c-bf76-8decc8645fee.png">

**Comment by nohn** [comment]
Warnings should be gone now.

**Comment by joab40** [comment]
Hi @nohn , thanx for doing a great job. :)
Sorry to say, but Last update same issue came back. Warnings is gone, but cant remove Post Decimal Digital digits. They pops back after 1-2s. when pressing "Remove a Digit". It also looks like "post decimal digits doesn't work" 

Best regards / Johan
